server.port=8083

spring.application.name=transaction-service

spring.datasource.url=jdbc:postgresql://localhost:5432/banking?currentSchema=transaction
spring.datasource.username=banking
spring.datasource.password=banking

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=transaction
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.schemas=transaction
spring.flyway.default-schema=transaction
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/docs

app.jwt.secret=${JWT_SECRET:ZmFzdC1kZXYtc2VjcmV0LWtleS1mb3ItYmFua2luZy1hdXRoLXNlcnZpY2UtMjAyNg==}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

app.account-service.base-url=http://localhost:8082

app.transfer.daily-limit=50000

app.internal.secret=${INTERNAL_SECRET:banking-internal-dev-secret}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

app.kafka.enabled=${KAFKA_ENABLED:true}
