server.port=8085

spring.application.name=audit-service

spring.datasource.url=jdbc:postgresql://localhost:5432/banking?currentSchema=audit
spring.datasource.username=banking
spring.datasource.password=banking

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=audit
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.schemas=audit
spring.flyway.default-schema=audit
spring.flyway.locations=classpath:db/migration
spring.flyway.create-schemas=true

management.endpoints.web.exposure.include=health,info

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/docs

app.jwt.secret=${JWT_SECRET:ZmFzdC1kZXYtc2VjcmV0LWtleS1mb3ItYmFua2luZy1hdXRoLXNlcnZpY2UtMjAyNg==}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=audit-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

app.kafka.enabled=${KAFKA_ENABLED:true}
